== Priority Area 1: Science and Research

_Improving biodiversity evidence for scientific research and understanding_

=== 1. Engage research communities for data mobilization and use

Nodes play an essential role in engaging with researchers within their countries and networks, promoting open science principles (in line with the https://en.unesco.org/science-sustainable-future/open-science/recommendation[UNESCO open science recommendation]) and building communities of data publishers and users. Research communities can help to identify data gaps, data needs, and challenges in the use of the available data that can help nodes to prioritize activities. Several nodes have succeeded in embedding GBIF within academic training programmes (see https://www.gbif.org/article/aA0MjVddRiRFOX2SEs7mT/[guiding example from Benin] and https://www.gbif.no/projects/biodata/[the BioDATA and BioDATA Advanced project]), developing capacity and encouraging new generations of researchers to follow open science practices. GBIF’s focus on thematic communities, continuing with thematic expert communities around GBIF thematic priorities, such as DNA-derived data,  disease vector data, invasive alien species, marine data, and agrobiodiversity will lead to growing interest in data publishing and data use from researchers that will seek to connect with nodes for support.

Nodes are encouraged to:

* Engage with scientific leaders in biodiversity sciences to build and develop a scientific community around the node. The https://www.gbif.org/resource/search?contentType=literature&literatureType=journal&relevance=GBIF_USED&peerReview=true[country filter] of literature tracking and annual https://www.gbif.org/science-review[_Science Review_] can help identify active users of GBIF-mediated data in the country.
* Encourage local researchers to join the https://www.gbif.org/ambassadors[biodiversity open data ambassadors programme^]. Cultivate active relationships between the node and ambassadors to promote GBIF data use in research through national and regional conferences and other relevant fora.
* Explore and consider participating in the https://www.gbif.org/news/3gm3lJaUQgTKZJRm6TiBff/[pilot DNA metabarcoding data programme^]to improve GBIF’s integration of DNA metabarcoding data on biodiversity. 
* Explore publishing event-based survey and monitoring data with Humboldt extension.
* Organize national or thematic events targeting research communities, including focus on training for DNA derived data and GBIF (see available https://doi.org/10.35035/doc-vf1a-nr22[guide^] and https://www.gbif.org/training[training materials^]).
* Promote and participate in data mobilization actions relating to thematic approaches, such as calls for data papers (see, for example, https://www.gbif.org/news/70AuWTs68FiGEZEyALB1TV/[current call for data papers relating to vectors of human diseases^]).
* Promote the https://www.gbif.org/data-use-club[Data Use Club^] within research and student communities as a means to develop data literacy skills, for example, by organizing a national/thematic team (see https://vimeo.com/711112378?embedded=true&source=vimeo_logo&owner=8757851[guiding example from Colombia^]).
* Engage with national graduate schools, universities and other key partners in higher education aiming at making data skills and GBIF training an essential part of university curricula (using the increasing popularity of teaching R and the https://www.gbif.org/article/aA0MjVddRiRFOX2SEs7mT[master’s programme in biodiversity informatics in Benin^] as examples).
* Increase promotion of the https://www.gbif.org/graduate-researchers-award[Graduate Researchers Award^] and https://www.gbif.org/ebbe[Ebbe Nielsen Challenge^] to encourage and recognize innovative research use of GBIF-mediated data.
* Support the development and implementation of national policies on open science and data to implement FAIR and CARE principles.
* Know, seek and develop key partnerships with national, regional, global and thematic research infrastructures to help drive the agenda around data-intensive biodiversity research.

== Priority Area 2: Policy and Partnerships

_Developing partnerships that benefit policy and society_

=== 2. Support national biodiversity commitments and the science-policy interface

Through partnerships and coordination, nodes can enable data flows into indicators and reporting processes relating to biodiversity status and trends, supporting commitments under the Convention on Biological Diversity (CBD) and the Sustainable Development Goals. By building linkages with the Intergovernmental Science-Policy Platform on Biodiversity and Ecosystem Services (IPBES), nodes can support biodiversity assessments by providing access to biodiversity data and enabling policy-related research based on GBIF-mediated data. These linkages can also support the nodes in terms of raising awareness of the value of open biodiversity data to national policy and commitments, as well as identifying policy-relevant gaps in data availability. +
Nodes are encouraged to:

* Make connections with the CBD focal points or even include them in their node team to support the implementation of national commitments under the Convention on Biological Diversity (CBD).
* Pay particular attention to the process of revising National Biodiversity Strategies and Action Plans (NBSAPs) that is ongoing in many countries, and developing national targets and indicators for reporting progress towards goals and targets of the Kunming-Montreal Global Biodiversity Framework (CBD), seeking advice from the Secretariat if required. For countries that have submitted NBSAPs, consider starting discussions with CBD focal points on what the data needs would be.
* Engage with the IPBES national focal points (see https://www.gbif.org/article/6Or2284ny8cU2SaAIok8Ug/[guiding example from Belgium]), OBIS regional and/or national nodes (in line with https://www.gbif.org/news/7w0xoodpNZRwnt1SjWfML0/obis-and-gbif-endorse-joint-strategy-and-action-plan-for-marine-biodiversity-data[OBIS and GBIF joint strategy and action plan for marine biodiversity data]), and with other biodiversity-related conventions to discuss data flows and known data gaps.
* Relate data use cases and other GBIF activities to supporting the Sustainable Development Goals (SDGs) (see https://www.gbif.org/article/TbnYdzigUnP08rQbcwh56/[guiding example from the Chinese Academy of Sciences]).

=== 3. Promote open biodiversity data approaches within the business and finance sectors

In recent years, several nodes have scaled up engagement with the private sector resulting in increased data mobilization, partnerships, and communication materials to support further engagement (see the resources developed and available for reuse through the https://www.gbif.org/project/2Zik1tfJoh3C92ZslvhDIr/[CESP OpenPSD project] and the https://www.gbif.org/business[GBIF business sector page^]).

Nodes are encouraged to:

* Engage with the private sector through sectoral associations, individual companies and consultancies to promote publishing of data associated with environmental and social impact assessments (ESIA) as well as ongoing biodiversity monitoring.
* Where appropriate and practical, support data publication from the private sector through guidance and use of data publishing platforms.
* Engage with national environment monitoring authorities to encourage mandatory publishing of primary biodiversity data through GBIF as part of the ESIA process (see resources developed by the https://www.gbif.org/project/83336/[CESP BIREME project]).
* Engage with development finance institutions  to promote requirements for data publication in projects supported by development finance or overseas development assistance, including through the https://www.gbif.org/data4nature[Data4Nature initiative] in consultation with the Secretariat.

== Priority Area 3: Community and Capacity

_Developing the GBIF network to meet future needs and challenges_

=== 4. Support node development through knowledge sharing and mobility of skills

Nodes play a central role in the GBIF network and ensuring capacity at the node level in terms of a skilled and stable node team remains a priority. Nodes are recommended to strive for a team of at least four full-time equivalents (FTEs) per country node, in line with the recommendations in the guidance on https://docs.gbif.org/effective-nodes-guidance/1.0/en/[Establishing an Effective GBIF Participant Node]. A node team would typically include a Node Manager, an IT-developer, a data manager and a node staff member for scientific outreach and communication. Recognizing that this is a combined responsibility with the Heads of delegation, Node managers will report on progress to establish such functional node teams.

Nodes benefit greatly from the sharing of knowledge and experience with other nodes in the network. The https://www.gbif.org/programme/82219/capacity-enhancement-support-programme[GBIF Capacity Enhancement Support Programme (CESP)] is a key mechanism for supporting collaborative projects between nodes.

GBIF is implementing a new phase of the https://www.gbif.org/programme/82243/bid-biodiversity-information-for-development[Biodiversity Information for Development (BID) programme], with funding from the European Union, to support capacity development to meet the knowledge needs of the Kunming-Montreal Global Biodiversity Framework. The programme aims to significantly improve data accessibility in the target regions and can support the establishment of new nodes.  In 2025, nodes will be encouraged to support calls for data mobilization projects in the target regions of Africa, Latin America & Caribbean, and Pacific, through promotion of the calls to interested parties, acting as reviewers and selection panel members, and mentoring support to BID programme applicants.

In 2025, Nodes will be invited to participate in the Global Nodes training and meeting, alongside the Living Data conference in Bogota, Colombia. The training will focus specifically on the needs of Node Managers, and the materials developed and used during the training will contribute to the overall Nodes development curriculum. The events will provide an important networking opportunity for exchange of skills and experiences among nodes and will contribute to developing new connections in the community, including with the other partner organizations involved in the Living Data conference. +
Nodes are encouraged to:

* Engage in communicating the value of GBIF, including making use of the https://www.gbif.org/news/5WZThcL928vmPnSvrGhZfE/[economic valuation of the GBIF network^], to potential partners at all levels.
* Collaborate with other nodes and partners to support active participation in GBIF by more countries.
* Support the onboarding of new nodes in the network.
* Consider sharing impact stories as part of the nomination process for the https://www.gbif.org/gbif-node-awards[GBIF node awards].
* Continue to collaborate with other nodes on capacity development, including through the https://www.gbif.org/programme/82219/[Capacity Enhancement Support Programme].
* Contribute to the consultations and preparation activities for the Global Nodes training and meeting.
* Continue training and engagement actions to strengthen and expand national data publication and use.
* https://www.survey-xact.dk/LinkCollector?key=4S38YXU4U1CK[Volunteer] within the GBIF community of practice and https://www.survey-xact.dk/LinkCollector?key=YR76Z62RU69K[log] active contributions during the year.
* Contribute to the promotion of the calls for proposals under the Biodiversity Information for Development (BID) programme, acting as reviewers and selection panel members, and supporting applicants where possible.
* Develop and enhance https://www.gbif.org/hosted-portals[hosted portals] and https://living-atlases.gbif.org/[Living Atlases] for national, regional and thematic data communities.
* Join and help establish an informal node communications interest group that meets quarterly to identify needs and share strategies for effectively communicating the value and impact of GBIF.

=== 5. Develop capacity within regional communities of practice

Since 2021, GBIF has contracted regional support teams in Africa, Latin America and the Caribbean, Asia, and most recently in Europe and Central Asia. The work of these teams focuses on geographic areas that are not yet supported by GBIF nodes and covers engaging data holding institutions, supporting data publishing, developing skills and engagement within the community of practice and providing feedback to GBIF on regional capacity needs. They can also provide ad-hoc support and specific training to existing GBIF nodes upon request. This approach complements the ongoing efforts of node managers, regional representatives, and volunteer trainers and mentors, to develop regional communities of practice engaged in data mobilization and use through GBIF. Nodes have an essential role in guiding the work of regional support teams and future regional-level support for capacity and participation.

Interregional partnerships under the umbrella of GBIF are encouraged to support more extensive capacity building and / or sound academic training of students in order to promote a new generation of data scientists capable of data use to inform decisions on biodiversity conservation and sustainable use across regions. +
Nodes are encouraged to:

* Partner with the regional support teams to support the work of the nodes, as well as broader capacity development in the region, and contribute to discussions on the future of this approach.
* Contribute to the development of future capacity development programmes, such as the possible expansion of the https://www.gbif.org/bid[Biodiversity Information for Development] (BID) programme.
* Participate in regional nodes meetings and discussions on strengthening regional engagement in GBIF, including preparations for regional nodes meetings in 2026.

== Priority Area 4: Infrastructure and data products

_Maintain and evolve infrastructure to advance biodiversity-related knowledge_

=== 6. Strengthen support services for collection communities

Nodes have been actively contributing to updating and enriching the content of the https://www.gbif.org/grscicoll[Global Registry of Scientific Collections] (GRSciColl), supported by videos and training activities. For institutions with collections that are not yet publishing data, updating their records in GRSciColl can be a simple first step towards engaging them as data publishers in the future. This work helps to raise the visibility of collections, including those that have not yet been digitized.

Nodes are encouraged to:

* Contribute actively to updating GRSciColl and engaging institutions with collections and relevant societies and networks in data mobilization.
* Participate actively in the 2025 https://scientific-collections.gbif.org/road-map[GRSciColl road map] focus on content enrichment for collection descriptors
* Support the development of https://www.gbif.org/hosted-portals[hosted portals] for collections.
* Test and provide feedback to training materials developed by GBIFS, and promote training with relevant editor groups.

=== 7. Contribute to data model enhancements

Community engagement is essential in the work on diversifying the data model, which, in turn, enables richer and deeper indexing of biodiversity data, and a stronger, more inclusive knowledge base. Case studies https://www.gbif.org/new-data-model[have been prepared] in collaboration with community members who have identified the need to better support the publishing of their specific type of biodiversity data. Work is now underway to evolve the Darwin Core Archive format with new data schemas to allow publishing of more expressive datasets using e.g. the IPT 3. The schemas and format are expected to form part of the Darwin Core standard.

The work will rely on community feedback, testing, and engagement through the nodes. Nodes, in their role of supporting data mobilization activities from their communities, will need training materials and documentation to allow them to efficiently promote data publishing via the new format. Ultimately, this should enable GBIF and nodes to provide the data infrastructure for a broader set of biodiversity data holders and users.

Nodes are encouraged to:

* Participate in the webinars to follow updates about the new data model.
* Engage in the development and testing of new training materials and documentation to support data publishing with the new data model.
* Identify priority directions and case studies that resonate best with their priorities (e.g. interactions data, metabarcoding data, surveys and monitoring etc.), and encourage holders of such data to work with GBIF in this area.
