[appendix]
== Participant plans 2025

Towards the end of each year, the GBIF Secretariat asks Participants to outline any work they have aligned to the priority areas identified in the GBIF’s work programme for the upcoming year. This appendix includes the plans Participants provided for 2025.

[[plans-priority-1]]
=== Priority Area 1

==== Andorra

In the coming year, we intend to continue to expand the database. Also, to incorporate data from new projects being developed since Andorran Research and Innovation.

==== Angola

1) Workshops to evaluate and validate the data and information collected from institutions linked to biodiversity and the environment.
2) Regional thematic seminars: ‘The use of the GBIF tool for the conservation, valorisation and dissemination of Angola's biodiversity’
3) Trainers' seminar on digitalisation: “The use of technology in record time, mobilisation and publication of data”; and 4) National/regional training (capacity building) for potential holders of biodiversity information.

==== Argentina

* Continuing with the development of the Biodiversity Data Portal of Argentina and expanding the addition of institutions (with the update or addition of information) to GrSCiColl are some of our priorities. 
* Being able to continue with the CESP projects, both related to GRSciColl (led by Ecuador) and Data Extension (led by Brazil) is another of the activities carried out in 2024 and that will continue in 2025.
* To be able to train and disseminate information about the publication of eDNA among our publishers.

==== Belgium

* ongoing support biodiversity data mobilization on soil freshwater, disease vector and monitoring
* One Health (BeOH) event: Ecosystems in the balance 22-23 Jan 2025
* MDT pilot programme eDNA community
* Atlas of Living Flanders to be launch this spring

==== Burundi

We first need capacity building to start the different activities.

==== Canadensys

- Continue to support Canadian publishers and helping the community to have access to well curated data from and about Canada
- Improve both Legume and Canadensys portal, specifically in regard of communication
- Develop a community of metabarcoding data publishers
- Continue to train students and research communities"

==== Colombia

* Participation in the pilot phase of the new Metabarcoding Data Toolkit (MDT) to add more eDNA publisher to the Network and fulfill datagaps.
* Mobilize local community monitoring data through the GBIF Network.
* Continue promoting the participation in the Data Use Club, as well as other calls like Ebbe Nielsen Challenge and the Graduate Researchers Award

==== Costa Rica

In this area, we will focus on attracting new major publishers as we did last year that help us to increase the volume of data published yearly in the country. For example, we hope to formalize the agreement with CCT and publish their first dataset. This movements will help to reduce the knowledge gaps that we have currently identified. Also, the node will keep working with researchers and projects related to DNA-derived data in the country in order to incorporate this information to GBIF.

==== Croatia

Croatian GBIF node will continue with mobilization of data from nature protection/conservation sector, both in its own capacities and in collaboration of experts from CroBIF network. An analysis/survey of existing biodiversity data in different thematic areas  (IAS, conservation, climate change) for mobilization will be implemented. GBIF Croatia continues the work on communicating the importance of open data and use of FAIR principles, including preparation of project that will incorporate educational activities on GBIF and data mobilization.

==== Denmark

Arter is in process with securing continued funding for further developments of features on the App and portal, incl. heightening of data quality from the portal.
DanBIF does not itself publish scientific papers, but strive to mobilise and publish datasets of scientific relevance on GBIF, and with the best possible data quality. Hence focus is on having even more datasets from the Natural History Museums in Denmark (incl. data resulting from the DaSSCo initiative). The Atlas Flora Danica dataset will be republished with exact geolocations instead of grid centerpoints. DanBIF continues piloting the Metabarcoding Data Toolkit, hopefully publishing many more datasets of this kind. DanBIF will give it's yearly lecture "GBIF, DanBIF, Digitisation and Conservation " at the University of Copenhagen Biology bachelor / masters course "Conservation". DanBIF and the Digital Section at NHMD will work on correcting / updating and enriching the information on GrSciColl about collections in Denmark, using Latimer Core.

==== Finland

FinBIF will seek to begin mobilising Finnish metabarcoding data using our Metabarcoding Data Toolkit installation and leveraging the GBIF Metabarcoding Data Programme along with our  in-country partner organisations. FinBIF plans to engage Finnish researchers to partner with us to incorporate ecological modelling into our suite of tools and services we offer through our national portal.

==== France

* Engagement with national research communities relating to data mobilization and use, targeting thematic priorities (eDNA, survey and monitoring data, vectors of human disease, marine data) and French overseas. (Arrival of one FTE in our department to work on French overseas data) 
* Participation in the pilot DNA metabarcoding data programme. (Arrival of one FTE in our department to work on this type of data) 
* Encourage publishing event-based survey and monitoring data with Humboldt extension.  
* Ongoing discussions with Biodiversa+ national team around data flows from survey and monitoring data communities
* Contribution on national working groups: WP Traits, WP Sequence and new WP Habitat
* Maintain and reinforce links with national aggregators (SIB, SINP) and research infrastructures (RI Recolnat for specimens, PNDB for research data biodiversity in RI Data Terra) 
* Keep track of use through GBIF monitoring and organization of a user survey.
* Prepare an event for the 20th anniversary of GBIF France in 2026.

==== Germany

GBIF node delegates node manager and staff plan to attend international meetings, among others GBIF ECA 2025 in Waterford (Ireland) and the GBIF conference „Living Data 2025“ in Bogota (Columbia) and will serve in several committees as before.

==== Madagascar

We had a problem with IPT hosting that is solved now and we will resume to format and publish these data (microorganisms: bacteria, fungi). We are also planning to publish media data (plant, animal).

==== Netherlands

===== Activity 1.1
NLBIF, together with KPMG, will develop a report on "Accelerate the use of biodiversity data in companies to map and report their biodiversity impacts and dependencies". Biodiversa+ tender https://www.biodiversa.eu/wp-content/uploads/2024/10/Call-for-tender_Accelerate-the-use-of-biodiversity-data-in-companies_Specifications-1.pdf.

===== Activity 1.2
* NLBIF aims to implement the Humboldt Extension for Ecological Inventories with several data publishers in 2025.
* NLBIF, through the BMD project, aims to contribute to the development of training materials on how to mobilise and use GBIF data.

===== Activity 1.3
* NLBIF through involvement in BMD and the MetaPlantCode projects will continue to mobilise and support the publication of eDNA datasets in 2025 and contribute to the further testing of the GBIF MDT.
* NLBIF through the MetaPlantCode project will contribute to indexing of ASVs.

===== Ongoing activities
NLBIF through the BMD project will contribute to the further development of community standards on eDNA data and camera-trap and audio data.

==== New Zealand

Building on the progress made in 2024, GBIF New Zealand will continue to strengthen data mobilisation efforts and stakeholder engagement to enhance the accessibility and application of biodiversity data for research, policy, and decision-making.  A focus on mobilisation of data on alien invasive species remains a priority in 2025, as New Zealand seeks to improve its biosecurity and biodiversity management frameworks. Planned activities include:

. GBIF-NZ and NZOR Stakeholder Workshop. 
* A key initiative for 2025 is the GBIF-NZ and New Zealand Organisms Register (NZOR) workshop, aimed at engaging key stakeholders, government agencies, and data holders.
* This workshop will serve as a platform to promote the value of GBIF in New Zealand and its role in enabling open biodiversity data, test and refine a national workplan for data mobilisation and strategy development, identify priority datasets for mobilisation, focusing on thematic areas such as invasive species, eDNA, and biodiversity monitoring.
. Strengthening Data Mobilisation Pathways
* Continued efforts will be made to enhance the mobilisation of biodiversity data via GBIF. 
* The New Zealand 2025 Work Programme will place particular emphasis on strengthening GBIF as part of our national data infrastructure and the use of GBIF biodiversity data into decision-making processes.
. Expanding data mobilisation to GBIF for pest management
* We will work across central and regional sector to extend current efforts to mobilise weeds and pest data to support NZ goals for system-wide prioritisation frameworks to tackle the increasing pressures of invasive and established pests.
* Support key agencies such as Ministry for Primary Industries (MPI) with the use of GBIF-mediated data in pest risk assessments and monitoring.
. Improve coverage and quality of data representation in GBIF from metabarcoding research and eDNA monitoring
* GBIF NZ node will support Wilderlab to progress plans to mobilise eDNA data to GBIF including development of data sharing agreements with partners and agencies.

==== Nordic Genetic Resource Center

We are working on DOIs and MCPD data implementation.

==== South Africa

Continue to drive the GBIF Graduate Researchers Award in South Africa.

==== Spain

Besides maintaining our ongoing activities regarding support for data publishers, and training for better using GBIF mediated data, in 2025 we plan to set in motion  a set of  time-bound projects such as:
1. "Tools and Strategies for Biodiversity Data Validation" that will include an Inventory with existing documentation and tools related to data quality, developing and refining some data validation tools, and a training workshop.
2. Evaluation of GBIF Use in Higher Education: The GBIF biodiversity data network is a widely used resource in the academic field. However, we still lack a detailed and quantitative assessment of its utilization in higher education, as well as a precise identification of its strengths and areas for improvement. This project aims to conduct a survey to obtain a representative picture of how GBIF is used and taught in universities.

==== Sweden

===== Activity 1.1
- Analyze knowledge gaps in Swedish data (taxonomic, spatial & temporal).
- Make updated data stakeholder analysis. 
- Mobilize new data and update existing datasets.
- Active outreach to stakeholders and data stewards on filling knowledge gaps. 
- Engage high-priority thematic communities - cultivate and support discussions, knowledge exchange and engagement (e.g. ILK/CARE principles, private sector, species interactions, molecular data communities).
- Promote best practices in data citation using digital object identifiers (DOIs). 
- Participate in- and co-organize relevant conferences/meetings/workshops (e.g. Oikos conference, SBDI infrastructure days).

====== Long term
- Look for opportunities for data mobilization project funds.

===== Activity 1.2
- Participate in DDLS activities and open calls when applicable.
- Participate in and encourage participation in TDWG activities and workgroups when applicable (e.g. interaction interest group, eDNA interest group).
- Promote and implement latest DwC best practice, terminology and controlled vocabulary 

===== Activity 1.3
- Continue engagement and improve coverage and quality of data representation in GBIF from metabarcoding research and eDNA monitoring.
- Participate in MDT pilot programme, community calls and training.
- Strengthen collaborations with barcoding communities (e.g. encourage Scilifelab to become participant organization in GBIF)

==== Tajikistan

This year I'm trying to do my best that Tajikistan stay voting country in GBIF and as I am Node Manager for GBIF in Tajikistan, its very important for my GBIF team in Tajikistan and totally in Central Asia.

[[plans-priority-2]]
=== Priority Area 2

==== Andorra

For the coming year, we must consolidate joint work with the Government of Andorra. Expand contacts with other partners, although Andorra is a small country and there are not many others.

==== Argentina

* Continue with the development of the Biodiversity Data Portal and resume contact with government institutions and relevant initiatives. At the moment the Portal has been included as an input in the National Biodiversity Strategy and we have scheduled meetings with the Foreign Ministry, the former Ministry of Environment of the Nation and similar.
* Continue supporting publishers, both with training and on-demand support.

==== Belgium

* Increase our links with our CHM, DiSSCo.be, LifeWatch.be
* Finish RipaRIAS project
* Engage BE experts in IPBES, IUCN workplan
* Promote open Biodiversity Data in the business sector

==== Burundi

Establish partnerships with countries and institutions already specialised in GBIF.

==== Colombia

* Enhance our involvement in updating the National Biodiversity Strategies and Action Plans (NBSAPs) by contributing data-driven insights and aligning with global biodiversity goals.
* Organize and host the Datos Vivos event, alongside serving as the host for the 32nd GBIF Governing Board meeting, fostering collaboration and knowledge exchange among global biodiversity stakeholders.
* Deepen engagement with the business sector by advancing efforts in data mobilization and promoting data utilization through the Biodiversidad y Desarrollo Colombia Network.

==== Costa Rica

Like the previous year, the node will continue making efforts to attract the attention of the productive sector (public and private). Thus, the companies will recognize GBIF as a important tool to store and share their data and contribute to knowledge and conservation of biodiversity.

==== Croatia

CroBIF will further encourage cooperation and joining the network, including through the meetings of public institutions for management of protected areas and encourage and support CroBIF participants in using available tools and publishing the data. We will continue to promote the use of available biodiversity data in policy planning and implementation.

==== Denmark

DanBIF continues to be actively involved in increasing the awareness of the importance and strength in the use and provision of data to GBIF towards the industry, financial sector and governmental agencies. DanBIF and Arter.dk will commence preparations towards having governmental nature monitoring data from aquatic environments shared in GBIF and on Arter.

==== Finland

In 2025 we plan to further strengthen ties and engagement at all levels of Finnish government and expand engagement with the private sector. FinBIF will continue to engage with key national stakeholders and actors working on Finland's commitments under the Convention on Biological Diversity, with a particular focus on the monitoring of progress on agreed goals and targets under the convention.

==== France

- Following the joint organization of the national French BON days in June 2024, continue to work with the French BON of GEOBON (lead by PNDB national pole of biodiversity data from the Ministry of Research and SIB Information system for biodiversity from the Ministry of Environment) 
- Present OBIS and GBIF joint strategy and action plan for marine biodiversity data and work with the French marine community, in particular the PNDB and ODATIS national poles of the Data Terra research infrastructure.
- Links with Biodiversa+: Strengthen the ties and follow the discussions around indicators and data flows from survey and monitoring data communities at national and European levels. Contribution to GINAMO project.  
- Continue engagement with the business and finance sectors to encourage sharing and use of biodiversity data: Data4Nature (AFD), DEPOBIO (legal repository of observational data from impact studies for private sector), international private companies based in France

==== Madagascar

We will continue to develop the synergy between entities (CHM, IPBS, COMBO+, IUCN,...)

==== Netherlands

===== Activity 2.1
NLBIF, together with KPMG, will develop a report on "Accelerate the use of biodiversity data in companies to map and report their biodiversity impacts and dependencies". Biodiversa+ tender https://www.biodiversa.eu/wp-content/uploads/2024/10/Call-for-tender_Accelerate-the-use-of-biodiversity-data-in-companies_Specifications-1.pdf.

===== Activity 2.2
- NLBIF is part of PBES-NL, the Dutch IPBES focal point and contributes to shaping its activities.
- The data cube technology developed by B-Cubed will be implemented in the BMD project.
- Through the BMD project indicators for EU biodiversity will be developed which contributes to GBF.

===== Activity 2.3
- NLBIF together with KPMG will develop a report on "Accelerate the use of biodiversity data in companies to map and report their biodiversity impacts and dependencies". Biodiversa+ tender https://www.biodiversa.eu/wp-content/uploads/2024/10/Call-for-tender_Accelerate-the-use-of-biodiversity-data-in-companies_Specifications-1.pdf.
- NLBIF/Naturalis together with KPMG continues with the development of THRIVE (Toolset for Hierarchical Reporting and Insightful Validation of Ecosystems - https://www.naturalis.nl/en/thrive)

==== New Zealand

. Strengthen National and International Engagement in GBIF
* Host the GBIF-NZ and NZOR stakeholder workshop to engage government agencies, research institutions, and data holders, refining New Zealand’s biodiversity data strategy.
* Promote New Zealand’s participation in GBIF global initiatives, including Kunming-Montreal GBF reporting, and strengthen our engagement in programmes such as Biodiversity Information for Development (BID).
. Enhance Data Mobilisation for Science, Policy and Management
* GBIF NZ focus is to work with agencies, CRIS and sector to support target 21 - …”  ensure that the best available biodiversity data, information and knowledge are readily available to decision-makers and other relevant actors to support informed biodiversity policy, planning and decision-making processes, as well as for monitoring:” 
* Mobilise priority datasets, focusing on invasive species, eDNA, and biodiversity monitoring, to improve data accessibility for science, policy, and environmental management.
* Support national and regional organisations in publishing biodiversity data via GBIF’s hosted IPT infrastructure and best practices, ensuring integration into CBD commitments.
. Build Partnerships for Science-Policy Impact
* Strengthen engagement with New Zealand’s CBD focal points to integrate GBIF-mediated data into NBSAP targets, biodiversity indicators, and national reporting frameworks.
* Engage with and support key agencies and stakeholders developing and maintaining national checklists and processes (e.g. NZ Red List of Ecosystems and the Global Register of Introduced and Invasive Species (GRIIS)).

==== Nordic Genetic Resource Center

We had 3 Nordic Conferences, 8 webinars and participated at the COP.

==== South Africa

South Africa is hosting the G20 in 2025, and the SANBI-GBIF Node will participate in the RIWG with GBIF as a knowledge Partner, driving aspects of Biodiversity for Sustainable Development.

==== Spain

Besides maintaining our ongoing activities regarding support for data publishers and training for better using GBIF mediated data, in 2025 we plan for setting in motion a set of  special projects such as:

. Biodiversity in numbers: a tool that integrates and visualizes key information about biodiversity, enabling analysis and decision-making based on up-to-date and accurate data.
. Spatial portal: This Spatial portal has been featured in GBIF node projects since 2021. It is currently operational at https://espacial.gbif.es/. This platform allows users to visualize species presence data in combination with environmental layers (such as climatic variables) and polygons (such as protected areas) on an interactive map. Additionally, it offers tools for performing basic combined analyses, such as the correlation between biotic and abiotic data, and for downloading these data for more complex studies.
. Collaboration Plan of the Global Community Atlas of Living Australia (ALA): The "Atlas of Living Australia (ALA)" platform is one of the most advanced bioenvironmental portals in the world, unique for its ability to integrate massive biological and environmental data to carry out visualizations and analyses. Additionally, it has an interface that attracts audiences ranging from primary education to citizen science and research. The GBIF Node in Spain was the first to adapt and adopt the ALA platform for its data portal (https://datos.gbif.es) in 2015. Currently, more than 10 national GBIF nodes have followed this path, and even more are considering its implementation. All of them form the "Living Atlases" community (https://living-atlases.gbif.org/). Both the core ALA programmers and the Living Atlases community continue to improve the platform and develop new functionalities. However, these developments often occur in a disconnected manner, leading to underutilization and frequent implementation incompatibilities. In this situation, better leveraging ongoing developments, improving collaboration to enhance efficiency, and creating a better platform become obvious necessities. To address these shortcomings in collaboration with GBIF-Sweden, GBIF-France and and the Flanders component of GBIF-Belgium we are leading a coordination strategy whose first milestone is the organization of an international technical workshop. See: https://gbif.es/en/talleres/ala-las-technical-workshop-madrid-march-2025/ 

==== Sweden

===== Activity 2.1
- Engage and participate in GBIF governance meetings and relevant conferences and training events.
- Continued work on outreach to SIDA (Swedish International Development Cooperation Agency).
- Outreach to GIDA-Sápmi (Global Indigenous Data Alliance)
- Mentor and train stakeholders in Ethiopia through funded CESP project.
- Investigate possibilities of applying for CESP mentoring in Lithuania.

====== Long term
- Promote GBIF being recognized as a key partner for biodiversity-related projects and as the global repository for biodiversity data (e.g. increase HoD engagement, nominate candidate(s) to strategic GBIF governing bodies, research proposal ad texts to promote dedicated budget on data mobilization, streamlined data management plan etc).
- Find special purpose funds for GBIF ILK work group/interest group.

===== Activity 2.2
- Monitor progress towards the goals and targets agreed through the CBD and integrated into national platforms and reporting processes.
- Follow up the Biodiversa+ biodiversity data mobilization from projects funded through the call (Swedish EPA are national funders).
- Promote partnerships between national nodes in international organizations and/or infrastructures (e.g. IPBES, GEO BON, OBIS, TDWG, EMBRC, DiSSCo, etc.)
- Publish the new Swedish red-list assessment expected to come out in 2025.

===== Activity 2.3
- Continue engagement in the group from the Business and Biodiversity Workshop.
- Investigate possible partnerships (Planetary Biology, KnowIT, FinBio, Thyréns etc.).
- Co-author a perspectives paper as a result from the Business for Biodiversity workshop.

==== Tajikistan

Writing regional projects for capacity building in Central Asia Region. More different data publications.

==== United Kingdom

NBN will continue to explore this area.

[[plans-priority-3]]
=== Priority Area 3

==== Andorra

The target for next year is the same as the one we set for this year. To solve the technical problems of gbif Andorra's own portal and to expand its database. As we said last year, The aim is to make the GBIF.ad portal more widely accessible to biodiversity managers in Andorra.

==== Angola

To be an effective full member.

==== Argentina

As mentioned above, we wish to continue the development of the portal and participation in the CESP projects already committed. We are going to disseminate and advise our publishers both on the new BID call and on the calls for volunteers and awards.

==== Belgium

* Facilitate hosted portals in Belgium
* Engage new data publishers/users, community building
* Install new Node manager and Data Officer
* Data publishing training

==== Burundi

Drawing up a national GBIF communication strategy.

==== Canadensys

* We are planning to organize a workshop about data sharing and usage for the CSBQ/QCBS community, as well as participate with the North America Steering Group to the development of an online training about metabarcoding.
* We intend to improve the channels of communication for both the Canadensys network and the Legume Phylogeny Working Group.

==== Colombia

* Maintain and update virtual training courses to reflect IPT updates and changes in the National Publication Model.
* Collaborate with Brazil and Argentina through the CESP2024-015 initiative to develop a data extension for documenting socio-biodiversity information.

==== Costa Rica

The node will continue to strengthen alliances with the different levels of government to improve data mobilization and use to country-level decision making. Also, the Node will continue to highlight the importance of open data, GBIF and the national platform, BIODATACR, through participation in workshops, symposia and emerging activities.

==== Croatia

Continue with organization of educative workshops, including through projects. Work on data standardization capacities within the node and capacity building for interested scientists and experts. Continue to involve new participants in CroBIF network.

==== Denmark

DanBIF continues to provide support, tools and advice to digitisation and datamobilisation projects from nature societies, researchers and museums. DanBIF continues to evolve the successful wiki for all aspects of how to share data in GBIF and in the national species portal Arter.dk. DanBIF continues to provide support to dataholders with data relevant for Arter, to import their legacy data into Arter, which are then autmatically published in GBIF as part of the Arter dataset. DanBIF continues to work on a Hosted Portal setup to showcase data shared by Denmark on GBIF in a national context.

==== Finland

* FinBIF will actively work on strengthening our local community of practice with training and workshops throughout 2025.
* We will work closely with GBIF Sweden and Ethiopian partners on our joint CESP project to build capacity within the Ethiopian biodiversity community.

==== France

- Continue training and workshops at national level and as mentors/trainers for the community
- Maintain IPTs for French and southern partners
- Development or enhancement of OpenObs, French data portal on species observation data build on Living Atlases
- Launch of the new GBIF France hosted portal in early 2025
- Communication on the launch of BID calls and assistance in setting up projects
- Prepare the Global Nodes training and Global Nodes meeting (as Chair of NSG)


==== Germany

The activities mentioned for 2024 will be continued and GBIF-related events and workshops in Germany and Kenya are in preparation or already held in January 2025.

==== Madagascar

* Applying for CESP funding (data use)
* Collaboration with other nodes (in Africa, or France)

==== Netherlands

===== Activity 3.1
- As GBIF is used as the main biodiversity data infrastructure by the BMD project NLBIF will be in the position to further promote its use in the EU biodiversity projects and research infrastructures landscape.
- GBIF will be used as the biodiversity data resource for the Biodiversity NL portal.

===== Activity 3.2
- NLBIF as deputy ECA representative will contribute to GB32 and the Living Data conference.
- Whenever possible NLBIF will pilot tools that emerge from the new data model.

===== Activity 3.3
- NLBIF as deputy ECA representative will contribute to GB32 and the Living Data conference.
- Whenever possible NLBIF will pilot tools that emerge form the new data model.

====== Ongoing activities
NLBIF will look into the option to develop a hosted portal for the collections community in the Netherlands


==== New Zealand

. GBIF NZ participant node
* To build a stronger and stable foundation for the GBIF NZ Node and enhance the data mobilization and use through the network, we would like to develop a proposal seeking support to formalise GBIF NZ node, its resourcing and to expand the number of GBIF NZ support roles.
. Indigenous Data Governance
* Building on the progress made in 2024 on Indigenous Data Governance, GBIF New Zealand will continue to support and advocate for Indigenous data governance. This includes participation at the in-person event will be held alongside the Global Nodes Meeting and Training on Indigenous data governance, where appropriate, contribute to the task group and supporting GBIF to pilot Local Contexts Traditional Knowledge Labels in the GBIF Data Model. 
* Review the current GBIF guidance and support materials for FAIR and CARE to evaluate improvements required in New Zealand to meet the needs for indigenous data governance, following 2023 consultation.

==== South Africa

Strengthen Partnership engagements with academia to determine the training needs and approaches.  Training through the SANBI-GBIF Biodiversity Informatics Research Hub at the University of the Free State.

==== Spain

Besides maintaining our ongoing activities regarding support for data publishers and training for better using GBIF mediated data, in 2025 we plan for setting in motion a set of special projects such as:
 
* Mobilization of Biodiversity Data from the Private and Third Sector: 
* Mobilizing biodiversity data from the business sector and the third sector (NGOs, foundations, etc.) on platforms like GBIF Spain offers multiple benefits for both organizations and the environment. For companies, publishing data under FAIR principles strengthens their commitment to sustainability and transparency, improving their reputation and corporate responsibility. Additionally, sharing this data enables more precise decision-making based on reliable information, helping to mitigate environmental risks and optimize project planning. For NGOs, this visibility amplifies the impact of their conservation efforts, facilitating strategic alliances and ensuring the sustainability of their projects in the long term.
* Incorporating this data into the GBIF portal improves the quality and diversity of records, positioning the platform as key in conservation. This collaboration ensures that biodiversity decisions are backed by high-quality data, increasing effectiveness in protecting species and ecosystems. Moreover, robust environmental indicators are created, essential for public policies and sustainable management strategies.
* The strategy to attract key actors from the business and third sectors will begin with identifying strategic industries, such as extractive, agricultural, and energy sectors; companies with sustainability certifications or social responsibility programs; and networks of NGOs focused on biodiversity conservation.

==== Sweden

===== Activity 3.1
- Highlight GBIF’s role as a data infrastructure and network that supports open data, open science and policymaking.
- Promote and support proposals to the hosted portal programme.
- Operate effective communication channels that produce and disseminate news items etc.
- Update the gbif.se web to include clearer information on CARE, data mobilization support etc. 

===== Activity 3.2
- Improve and strengthen the national foundation for data mobilization and use through the national network.
- Lead CESP on mentoring and capacity building in Ethiopia and further promote BID project proposals in the region.

===== Activity 3.3
- Investigate further engagement in CESP 
- Participate in Global Nodes Training (possibly as a trainer)
- Organize museum workshop on data standardization.

==== Tajikistan

Opening Host portal in Tajikistan.

==== United Kingdom

Subject to Business Case Approvals, we are anticipating an April 2026 start to DiSSCo UK's 10 year programme of digitisation, and in March 2025 will launch our first Expression of Interest in relation to establishing Digitisation Hubs across the UK. We continue to use our GBIF hosted Portal as a gateway to represent UK collections data, and the GRSciColl database to on-ramp institutions, including an active programme of data curation to support this process. The inability to represent Earth Science collections within this ecosystem remains a significant barrier to engagement by some UK based natural science collections. 

[[plans-priority-4]]
=== Priority Area 4

==== Andorra

Re-establish contacts with neighbouring Nodes and the ALA community to solve our problems with our own data portal (Gbif.ad). Hopefully our Node manager will be able to return to his job and then Andorra will be able to participate again in the GBIF community events and joint meetings.

==== Argentina

* Improve and complete the information in the Biodiversity Data Portal, adding information about GrSciColl, training and materials generated and news from the community.
* For a few years now, we have been participating in training for paleontological collections, which we hope to continue expanding. Likewise, a number of geological collections have approached the node and we hope to support them and foster their links with peers within the GBIF community.

==== Belgium

* Maintain GBIF Registry and GRSciColl
* Support for the unified model (use case)
* use GBIF literature tracking to feed our Belgian Experts Registry

==== Burundi

Drawing up a national GBIF communication strategy and capacity building to start the different activities.

==== Canadensys

In 2025, we will work on the addition of recent phylogenies within the Legume Data Portal Phylogeny Explorer, and we will continue to maintain and improve the Canadensys and LPWG hosted portals.

==== Colombia

* Update all eight IPT instances to enhance functionalities and provide feedback during the development and implementation of IPT version 3.1.
* Continue supporting national proposals for hosted portals, including the one from Universidad Nacional de Colombia.
* Actively contribute to updating GRSciColl and engaging institutions with collections.
* Update the contents and functionalities of the National Hosted Portal Biodiversidad.co to incorporate new developments.

==== Costa Rica

Finishing the migration of the BIODATACR platform to the cloud that will help to improve the service. Complete the development of the Mesoamerican Biodiversity Hosted Portal that will be important for the publishing of the mesoamerican biodiversity. Specially, in those countries where there is not a node established. Also, the work of improving the knowledge of the different sectors about GBIF and its services is constantly being carried out.

==== Croatia

Continue the work on national biodiversity database (BioAtlas) as a part of Nature Protection Information System. Ensure continuous availability of Bioatlas for wider public as well as quantity and quality of published data.

==== Denmark

DanBIF and the digital Collection Section with DaSSCo at the NHMD will continue ue to improve the content in GRSciColl regarding Danish natural history collection. DanBIF  will organise the publishing of more datasets based on the new GBIF data model (camera trap and Metabarcoding). DanBIF  and DaSSCo continues work on retiring  old static museum datasets and replacing them dynamic datasets being synchronised with museum collection management systems.

==== Finland

In 2025 we plan to update and improve the Finnish data in the Global Registry of Scientific Collections. A revision to our Checklist of Finnish Species will be published to ChecklistBank. We will continue with the development of our web portal in 2024 including adding a new species trait database.

==== France

- Update of TAXREF, national checklist 
- Continue to improve the description of French collections in GRSciColl, the Global Registry of Scientific Collections, and collaborate with national RI Recolnat on content enrichment for collection descriptors
- Continue to inform on new data model and engage participation on data model use cases (in particular around eDNA pilot tool)
- Improvement of national IT infrastructure: maintenance of OpenObs, a French observational data portal based on LA portals. Participation in the ALA-LAs Workshop to be held in Madrid in March 2025. 

==== Germany

* GBIF Germany is looking for data publishers that hold sampling event datasets and might support them to implement the new Humboldt extension (in cooperation with NFDI4Biodiversity)
* We will promote the use of metadata standards, standardized values, including vocabularies, agreed taxonomies and technical specifications (in cooperation with NFDI4Biodiversity)
* We will cooperate towards a new  DwC-A standard including the concept of frictionless data
* The mapping of ABCD datasets for GBIF will be further evaluated including the constraints in relation to of EML metadata information on agent roles and associated parties. 
* The implementation of an IndExs service API with relation to examplary GBIF occurrence data is in progress.

==== Madagascar

* Search for funding opportunity for the acquisition of powerful computer equipment
* Improve data quality and diversify data for users (researchers, policy makers, students, NGOs etc...)

==== Netherlands

===== Activity 4.1
- Together with B-cubed the use of data cubes will be further explored in the BMD project
- Through the BMD project ChecklistBank will be used to harmonise taxonomies across EU member states.

===== Activity 4.2
- Guidelines for taxonomic checklists will be piloted for the Dutch Species Register
- Curate the Dutch collections GRSciColl records
- Implement the use of controlled vocabularies for the Dutch collection records in GRSciColl

===== Activity 4.3
- NLBIF will continue with providing feedback on the Metabarcoding Data Toolkit (MDT)

===== Activity 4.4
- The use of camtrap dp will be extensively tested through the BMD project.

==== New Zealand

* To enable the use of GBIF to meet NZ national and regional reporting needs (e.g. GBF Target 6) and infrastructure needs (e.g. to underpin the Smart Weed Alert Tool (SWAT)), we need to work on the GBIF taxonomy backbone and The Global Register of Introduced and Invasive Species GRIIS list. We would like to explore the adoption of ChecklistBank for GBIF NZ including options for NZOR to publish up to date taxonomic checklists for the New Zealand biota.
* As resources permit, work with Local Context to promote the use of Biocultural and Traditional Knowledge Labels and Notices, and (as appropriate) work with data providers to include these in their mobilised data.

==== South Africa

Further efforts around DNA-derived data publication.

==== Spain

Besides maintaining our ongoing activities regarding support for data publishers and training for better using GBIF mediated data, in 2025 we plan for setting in motion a set of special projects such as:
 
National biodiversity Infrastructures day: Biodiversity data is generated from multiple sources and used in various scientific fields (ecology, taxonomy, conservation, health, agronomy, etc.), and its access is key for policy and management (CBD, Green Deal, Sustainability, Technology, etc.). From this strategic combination of necessity and potential, initiatives have emerged to acquire, aggregate, and serve biodiversity data. Often originating internationally, these initiatives reflect the national context in which they are called to play a relevant role in addressing scientific and social challenges. However, these initiatives often develop in parallel, focusing on their immediate objectives, with competition sometimes prevailing over collaboration, leading to inefficiencies and missed opportunities for cooperation. To address this, we propose organizing technical workshops that bring together these initiatives to better understand what we do, identify collaboration opportunities, and minimize duplications and frictions. Some of the initiatives we aim to bring together include ESFRI environmental infrastructures like LifeWatch, DiSSCo, and eLTER, especially their national nodes, citizen science initiatives, scientific data initiatives like EOSC or RDA , and administrations.

==== Sweden

===== Activity 4.1
- Keep up to speed with IPT versioning.
- Continuously improve data quality.

===== Activity 4.2
- Build and support a more responsive and active help desk team 
- Have a dedicated data mobilization support event/group – e.g. open office once a month 
- Improve technical documentation and collaborate with SBDI Support center and data mobilization group (especially related to the newly established GBIF technical documentation site) 
- Support data publishers through IPT, data formats, error diagnostics and custom metrics.
- Support training via webinars, individual appointments, documentation, videos and workshops.
- GRSciColl revision, improvements and outreach to stakeholders.
- Train new GBIF Sweden data steward.

===== Activity 4.3
- Participate in the pilot phase of the eDNA Publishing Tool (MDT).
- Stay updated on the exploration of the task group on Indigenous data governance, such as adopting Local Context labels at suitable levels within the GBIF infrastructure.

===== Activity 4.4
- Participate in and encourage participation in TDWG activities and workgroups when applicable (e.g. interaction interest group, eDNA interest group).
- Promote and implement latest DwC best practice, terminology and controlled vocabulary 

==== Tajikistan

Support data publication through IPT, data formats, error diagnostics and custom metrics.
